### ISSUE TITLE
Version change.

### ISSUE THREAD

**Issue by theochino** [Gnucash/gnucash-on-windows#2]
Line 112's version need to be updated from to in "defaults.sh"
  set_default MINGW_RT_VERSION "3.20-2"
to 
  set_default MINGW_RT_VERSION "3.21"

The README should add some blurb about how mingw will explode if the version is not right.
http://youtu.be/6miJ9YeK6no

I tough there was something wrong with my VMWare. This is more a mingw bug than anything else. 
But worth nothing so we don't spend hours looking in the wrong place.

![vlcsnap-2015-03-21-15h50m07s122](https://cloud.githubusercontent.com/assets/5959961/6766582/191f8400-cfe2-11e4-9a67-d7191ca340e1.png)

![vlcsnap-2015-03-21-15h50m19s141](https://cloud.githubusercontent.com/assets/5959961/6766583/232cf414-cfe2-11e4-8f9b-9b2ed6fab1e5.png)

**Comment by jralls** [comment]
Please refile this at bugzilla.gnome.org in Project Gnucash. You can use this [template](https://bugzilla.gnome.org/enter_bug.cgi?alias=&assigned_to=gnucash-core-maint%40gnome.bugs&attach_text=&blocked=&bug_file_loc=http%3A%2F%2F&bug_severity=normal&bug_status=NEW&cf_gnome_version=---&comment=&component=Build%20system&contenttypeentry=&contenttypemethod=autodetect&contenttypeselection=text%2Fplain&data=&defined_groups=1&dependson=&description=&form_name=enter_bug&gnome_attachment_status=none&keywords=&maketemplate=Remember%20values%20as%20bookmarkable%20template&op_sys=Windows&product=GnuCash&qa_contact=gnucash-core-maint%40gnome.bugs&rep_platform=Other&short_desc=&version=unspecified). We don't use the Github issue tracker; its being enabled on this repo was an oversight.
